### ISSUE TITLE
Terminal.Gui Windows aren't well implemented.

### ISSUE THREAD

**Issue by BDisp** [snapsinazfs/snapsinazfs#33]
The siaz-1.1 branch is failing with the [PR #2778](https://github.com/gui-cs/Terminal.Gui/pull/2778), see the comments [here](https://github.com/gui-cs/Terminal.Gui/issues/2775#issuecomment-1684180117).
Also you don't need to use `Application.RootKeyEvent` for the menu's shortcuts. You need to use upper case. The Ctrl+Z is absorbed by the `TextField` to undo and so is better adding Alt key. We must not avoid a view to receive a shortcut, unless we real want that.

**Comment by dodexahedron** [comment]
Thanks!

Good catch on the ctrl-z. I'll probably change that shortcut to something else so it's just a `ctrl+__` like the rest.

So are all key events received as upper case, then?

**Comment by BDisp** [comment]
> So are all key events received as upper case, then?

Because the Ctrl key is catch as 1 to 26 and to get the corresponding other key we add 64. So 1+64=65 which is the 'A' char and 26+64=90 which is the 'Z' that are all as upper case.

**Comment by dodexahedron** [comment]
Merged in #34 and calls to LayoutSubviews re-inserted, to be removed once Terminal.Gui with your fix is released.

Thanks again!
