### ISSUE TITLE
Bug in the HideZfsConfigurationWindow method.

### ISSUE THREAD

**Issue by BDisp** [snapsinazfs/snapsinazfs#35]
It have "Show _Template Configuration Window" and it should be "Show _ZFS Configuration Window" if you want to preserve the _Z hotkey.

**Comment by dodexahedron** [comment]
Oops good catch.

Don't know how that one slipped through for so long. 😅

Thanks

**Comment by dodexahedron** [comment]
I actually also intentionally left off the _Z for the new one, since it doesn't match up with the new shortcut I picked (ctrl+D), just to avoid confusion.

**Comment by dodexahedron** [comment]
Fixed in 21990da9573d0ff8c364bbf12485e21fc7f3a10e

Closing this one
